### ISSUE TITLE
Google Play Published

### ISSUE THREAD

**Issue by hungvu193** [nitink133/Instagram-Profile-Downloader#3]
Would it be easier to update if you publish it on google play?

**Comment by nitink133** [comment]
@hungvu193 Currently, I'm working on some more features then We'll publish it on play-store.

**Comment by mucahidkambur** [comment]
@beNitinhere bro your store key password is visible in app/build.gradle

**Comment by nitink133** [comment]
@mucahitkambur Oh no man, that's not the real one.
