### ISSUE TITLE
Instagram Live 

### ISSUE THREAD

**Issue by Amirhf1** [nitink133/Instagram-Profile-Downloader#5]
What solution do you have for downloading live?

**Comment by nitink133** [comment]
Hi @Amirhf1, sorry for the late response.
I didn't try this but I guess you can easily download them using your session id and stream URL.

**Comment by Amirhf1** [comment]
Thanks @beNitinhere for my help working on your project.

**Comment by nitink133** [comment]
@Amirhf1 You're welcome :)

**Comment by Amirhf1** [comment]
@beNitinhere 
In this app, I didn't notice the API 
Exactly how it connects to Instagram even without API

**Comment by nitink133** [comment]
@Amirhf1 Actually Instagram does not provide APIs for stories, posts, and others so I perform web-scraping using user-auth session id.
