### ISSUE TITLE
get username and etc...

### ISSUE THREAD

**Issue by Amirhf1** [nitink133/Instagram-Profile-Downloader#9]
how to get a username from **InstagramOfficalLoginActivity.java** 

I feel that this code does not work
```
 if (url.equalsIgnoreCase(mURL)) {
                    view.addJavascriptInterface(new MyBridge(InstagramOfficalLoginActivity.this), "bridge");
                    String javascript = "javascript: document.getElementsByClassName(\"_0mzm- sqdOP  L3NKy       \")[0].onclick = function() {\n" +
                            "        var username = document.getElementsByName(\"username\").value;\n" +
                            "        var password = document.getElementsByName(\"password\").value;\n" +
                            "        bridge.saveData(username, password);\n" +
                            "    };";
                    view.loadUrl(javascript);
                }

```

Do you have a better solution for getting a username?

**Comment by nitink133** [comment]
Hi @Amirhf1 , First of all, sorry for this late response, and yeah actually I'm saving user profile model in preference while handling cookies in the same activity

**Comment by Amirhf1** [comment]
Thank you for your answer.
Instagram has changed its html element elements

**Comment by nitink133** [comment]
Yes, I think so, Will update it soon and I request you too If you've sm time plz fix this and create PL will merge that in master
